language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
before_script: composer install
script:
    - ./vendor/bin/phpunit tests/
after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
notifications:
  email: false
